-- Widen ticker columns from VARCHAR(10) to VARCHAR(128)

ALTER TABLE news_signals ALTER COLUMN ticker TYPE VARCHAR(128);
ALTER TABLE positions ALTER COLUMN ticker TYPE VARCHAR(128);
ALTER TABLE open_orders ALTER COLUMN ticker TYPE VARCHAR(128);
ALTER TABLE decisions ALTER COLUMN ticker TYPE VARCHAR(128);
ALTER TABLE theses ALTER COLUMN ticker TYPE VARCHAR(128);
ALTER TABLE documents ALTER COLUMN ticker TYPE VARCHAR(128);
